<?php
return [
    'admin_id' => 'rst@yamada',
    'admin_pass' => 'yamadaPass',
    'err_001' => '入力内容が正しくありません',
    'title'=> 'RSTモニタシステム',
    'page_title'=>array(
        'facility' => '(施設登録)',
        'facility_mng' => '(施設管理者登録)',
        'viewer' => '(閲覧者登録)',
        'patient' => '(患者登録)',
    ),
    'btn'=>array(
        'facility' => '施設登録',
        'facility_mng' => '施設管理者登録',
        'viewer' => '閲覧者登録',
        'patient' => '患者登録',
        'regist' => '登録',
        'edit' => '編集',
        'cancel' => 'キャンセル',
        'update' => '更新',
        'delete' => '削除',
        'logout' => 'ログアウト',
    ),
    'label'=>array(
        'facility_name' => '施設名',
        'facility_id' => '施設ID',
        'facility_manager' => '施設管理者',
        'patient_count' => '患者数',
        'regist_status' => '登録済み',
        'setting_status' => '設置済み',
        'monitor_status' => 'モニタ中',
        'treatment_status' => '治療済み',
        'facility_manager_name' => '施設管理者名',
        'facility_manager_id' => '施設管理者ID',
        'password' => 'パスワード',
        'contact' => '連絡担当',
        'mail_address' => 'eメールアドレス',
        'facility_name_id' => '施設名/施設ID  ',
    ),
    'text'=>array(
        'circle' => '〇',
        'input' => 'を入力してください。',
        'delete' => 'を削除しますか。',
    ),
    'msg'=>array(
        'input' => '入力してください。',
        'symbol' => '※記号入力不可',
        'facility_regist' => '施設を登録してください',
        'err_001' => 'ID、パスワードが正しくありません。',
        'err_002' => 'パスワードが正しくありません。',
    ),
    //トークンミスマッチ
    'tkn_missmuch' => "セッションが切れました。<br>お手数ですがシェアアプリを<br>再起動してください。",
];